/**
 * Content generated by '{project-root}/node-scripts/VersionNumberReadStream.js'.
 * Generated Mon Jan 15 2018 16:01:34 GMT-0500 (Eastern Standard Time) 
 * @memberOf fjl
 */

export let version = '0.19.4';

export default version;

