/**
 * Content generated by '{project-root}/node-scripts/VersionNumberReadStream.js'.
 * Generated Fri Oct 06 2017 13:56:18 GMT-0400 (EDT) 
 */

export let version = '0.16.1';

export default version;

