/**
 * Content generated by '{project-root}/node-scripts/VersionNumberReadStream.js'.
 * Generated Wed Sep 27 2017 22:51:14 GMT-0400 (Eastern Daylight Time) 
 */

export let version = '0.14.89';

export default version;

