/**
 * Content generated by '{project-root}/node-scripts/VersionNumberReadStream.js'.
 * Generated Sat Aug 12 2017 19:30:43 GMT-0400 (Eastern Daylight Time) 
 */

export let version = '0.13.3';

export default version;

