# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: monorepo-build

on:
  push:
    branches: [ monorepo ]
  pull_request:
    branches: [ monorepo ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    env:
      NODE_ENV: CI/CD
      PUPPETEER_EXE_PATH: $(which chrome)

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: pnpm-setup
        uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: pnpm ci
      - run: pnpm test
