# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
# and https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-the-npm-registry .

name: Publish

on:
  release:
    types: [created]

jobs:
  build-test-publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: npm ci
      - run: npm run link-and-build:packages
      - run: cd packages/fjl && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          PUPPETEER_EXE_PATH: $(which chrome)
